Create sqlite without spectrum
iomega/ms2query pull request #142
Opened 2022-06-03 12:59 UTC by niekdejonge

Currently the spectrum ids from the metadata are used for creating new libraries.
These are available for GNPS spectra, but this creates an issue, when you want to add your own spectra to the library. 
Solution create integers as spectrum ids, instead of using the ones in the metadata.

2022-08-15 11:45 UTC, niekdejonge commented
@florian-huber This pull request changes the way library spectra are stored. Instead using the GNPS spectrum ids, now integers will be generated that are used as spectrum id. Could you maybe do a review to make sure I am not breaking anything by accident?

2022-08-17 11:11 UTC, florian-huber commented on ms2query/library_files_creator.py
> +        # assert list_of_spectra[0].get(self.settings[
Why comment out?
I would either keep or remove this.

2022-08-17 11:12 UTC, florian-huber commented on ms2query/library_files_creator.py
> +            # spectrum_id_column_name=self.settings["spectrum_id_column_name"]
Same here: keep or remove.

2022-08-17 11:15 UTC, florian-huber commented on ms2query/library_files_creator.py
> +        spectrum_ids = list(range(len(self.list_of_spectra)))
```suggestion
        spectrum_ids = np.arange(0, len(self.list_of_spectra))
```

2022-08-17 11:19 UTC, florian-huber requested changes
Looks good Niek!
Just a few minor code cleaning things in my suggestions.

2022-08-22 11:38 UTC, merged