Load s2v model
iomega/ms2query pull request #15
Opened 2020-11-06 15:19 UTC by louwenjjr

2020-11-07 08:56 UTC, florian-huber commented on ms2query_app.py
> +                     library_spectrums]
That is the same as in #14 right? Just see my comment there on moving this part into an own function.

2020-11-07 08:58 UTC, florian-huber commented
Nice progress Joris!
When running the app it worked fine when I entered a path, but it didn't when I drag/dropped or browsed the file.

2020-11-07 08:59 UTC, florian-huber requested changes
Nice additions!
Some extra changes would be nice, see comments.

2020-11-09 08:22 UTC, louwenjjr commented
> Nice progress Joris!
> When running the app it worked fine when I entered a path, but it didn't when I drag/dropped or browsed the file.

My idea was to add the model file via the drag/drop box and then add the directory of the model file with entering a path. But with this comment I think it makes more sense for now to just enter the path to the model.

2020-11-09 08:35 UTC, florian-huber commented
I agree, I think for now entering a path should be fine!
And it also makes me realize that we should at some point discuss the exact scope of a first prototype app. For instance, is it necessary to import an own library and model, or do we just provide defaults to try it out? But let's have those discussions elsewhere :)

2020-11-09 15:38 UTC, florian-huber commented on ms2query_app.py
> +model_file = st.sidebar.text_input("Enter path to Spec2Vec .model file:")
```suggestion
model_file = st.sidebar.text_input("Enter filename of Spec2Vec model (with path):")
```

2020-11-09 15:40 UTC, florian-huber approved these changes
Looking good!
Just had a minor comment on some text field.

2020-11-09 16:02 UTC, merged